[book]
title = "The jot.lua book"
description = "Goes over the jot.lua extension for neovim"
authors = ["Chris Pecunies"]
language = "en"
multilingual = false
src = "src"

# [output.css]
# additional-css = ["book.css"]


[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true
extra-watch-dirs = []

[output.html]
mathjax-support = true
default-theme = "ayu"
preferred-dark-theme = 'ayu'
copy-fonts = true
# additional-js = "book.js"
smart-punctuation = true
no-section-label = false
git-repository-url = 'github.com/clpi/jot.lua'
edit-url-template = "https://github.com/clpi/jot.lua/edit/master/book/{path}"
git-repository-icon = "fa-github"
input-404 = "404.md"

[preprocessor.pagetoc]

[output.html.search]
enable = true
expand = true
limit-results = 50


[output.html.playground]
editable = true

[output.html.fold]
enable = true
level = 0
